"""add missing fk indexes

Revision ID: 038e25c5619a
Revises: 2b309ba0e37e
Create Date: 2026-04-12 13:22:07.481076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038e25c5619a'
down_revision: Union[str, None] = '2b309ba0e37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lender_payables_lender_id'), 'lender_payables', ['lender_id'], unique=False)
    op.create_index(op.f('ix_lender_payables_report_id'), 'lender_payables', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_requests_branch_id'), 'report_requests', ['branch_id'], unique=False)
    op.create_index(op.f('ix_report_requests_vendor_specified_id'), 'report_requests', ['vendor_specified_id'], unique=False)
    op.create_index(op.f('ix_request_acceptances_report_id'), 'request_acceptances', ['report_id'], unique=False)
    op.create_index(op.f('ix_vendor_earnings_lender_id'), 'vendor_earnings', ['lender_id'], unique=False)
    op.create_index(op.f('ix_vendor_earnings_report_id'), 'vendor_earnings', ['report_id'], unique=False)
    op.create_index(op.f('ix_vendor_earnings_vendor_id'), 'vendor_earnings', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_earnings_vendor_id'), table_name='vendor_earnings')
    op.drop_index(op.f('ix_vendor_earnings_report_id'), table_name='vendor_earnings')
    op.drop_index(op.f('ix_vendor_earnings_lender_id'), table_name='vendor_earnings')
    op.drop_index(op.f('ix_request_acceptances_report_id'), table_name='request_acceptances')
    op.drop_index(op.f('ix_report_requests_vendor_specified_id'), table_name='report_requests')
    op.drop_index(op.f('ix_report_requests_branch_id'), table_name='report_requests')
    op.drop_index(op.f('ix_lender_payables_report_id'), table_name='lender_payables')
    op.drop_index(op.f('ix_lender_payables_lender_id'), table_name='lender_payables')
    # ### end Alembic commands ###
