"""add locality table and listing locality_id

Revision ID: 0630bde9396d
Revises: 69118841ebe4
Create Date: 2026-04-13 03:59:52.249916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0630bde9396d'
down_revision: Union[str, None] = '69118841ebe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pin_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'pin_code', name='uq_locality_name_pin_code')
    )
    op.create_index(op.f('ix_localities_city'), 'localities', ['city'], unique=False)
    op.create_index(op.f('ix_localities_pin_code'), 'localities', ['pin_code'], unique=False)
    op.add_column('listings', sa.Column('locality_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_listings_locality_id'), 'listings', ['locality_id'], unique=False)
    op.create_foreign_key(None, 'listings', 'localities', ['locality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_index(op.f('ix_listings_locality_id'), table_name='listings')
    op.drop_column('listings', 'locality_id')
    op.drop_index(op.f('ix_localities_pin_code'), table_name='localities')
    op.drop_index(op.f('ix_localities_city'), table_name='localities')
    op.drop_table('localities')
    # ### end Alembic commands ###
