"""add quality review table and gtr_review status

Revision ID: 1b37bc0f1445
Revises: a08c82469283
Create Date: 2026-04-13 04:10:49.017557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b37bc0f1445'
down_revision: Union[str, None] = 'a08c82469283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add GTR_REVIEW to existing reportstatus enum
    op.execute("ALTER TYPE reportstatus ADD VALUE IF NOT EXISTS 'GTR_REVIEW' AFTER 'READY_TO_PUBLISH'")

    op.create_table('quality_reviews',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'RETURNED', 'FLAGGED', name='qualityreviewstatus'), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_reviews_report_id'), 'quality_reviews', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_reviews_report_id'), table_name='quality_reviews')
    op.drop_table('quality_reviews')
    # ### end Alembic commands ###
