"""phase5 add listing pin_code vendor_count and report_purchases table

Revision ID: 24b913a88d37
Revises: 5d2ef40d3403
Create Date: 2026-04-10 11:25:55.609633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b913a88d37'
down_revision: Union[str, None] = '5d2ef40d3403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_purchases',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('lender_id', sa.Uuid(), nullable=False),
    sa.Column('purchased_by', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['purchased_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'lender_id', name='uq_purchase_report_lender')
    )
    op.add_column('listings', sa.Column('pin_code', sa.String(length=10), nullable=False))
    op.add_column('listings', sa.Column('vendor_count', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_listing_pin_code_property_type', 'listings', ['pin_code', 'property_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_listing_pin_code_property_type', 'listings', type_='unique')
    op.drop_column('listings', 'vendor_count')
    op.drop_column('listings', 'pin_code')
    op.drop_table('report_purchases')
    # ### end Alembic commands ###
