"""add config tables for phase 12b

Revision ID: 2b309ba0e37e
Revises: 3a9487f0bd13
Create Date: 2026-04-12 12:12:53.098628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b309ba0e37e'
down_revision: Union[str, None] = '3a9487f0bd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lender_config',
    sa.Column('lender_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lender_id', name='uq_lender_config_lender')
    )
    op.create_index(op.f('ix_lender_config_lender_id'), 'lender_config', ['lender_id'], unique=False)
    op.create_table('lender_vendor_preferences',
    sa.Column('lender_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lender_id', 'vendor_id', name='uq_lender_vendor_pref')
    )
    op.create_index(op.f('ix_lender_vendor_preferences_lender_id'), 'lender_vendor_preferences', ['lender_id'], unique=False)
    op.create_index(op.f('ix_lender_vendor_preferences_vendor_id'), 'lender_vendor_preferences', ['vendor_id'], unique=False)
    op.create_table('system_config',
    sa.Column('vendors_per_broadcast_round', sa.Integer(), nullable=False),
    sa.Column('broadcast_accept_window_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_accept_days', sa.Integer(), nullable=False),
    sa.Column('max_upload_size_mb', sa.Integer(), nullable=False),
    sa.Column('required_report_fields', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_config',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('auto_listing_enabled', sa.Boolean(), nullable=False),
    sa.Column('price_threshold', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('separate_valuation_legal', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', name='uq_vendor_config_vendor')
    )
    op.create_index(op.f('ix_vendor_config_vendor_id'), 'vendor_config', ['vendor_id'], unique=False)
    op.create_table('vendor_lender_exclusions',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('lender_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', 'lender_id', name='uq_vendor_lender_exclusion')
    )
    op.create_index(op.f('ix_vendor_lender_exclusions_lender_id'), 'vendor_lender_exclusions', ['lender_id'], unique=False)
    op.create_index(op.f('ix_vendor_lender_exclusions_vendor_id'), 'vendor_lender_exclusions', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_lender_exclusions_vendor_id'), table_name='vendor_lender_exclusions')
    op.drop_index(op.f('ix_vendor_lender_exclusions_lender_id'), table_name='vendor_lender_exclusions')
    op.drop_table('vendor_lender_exclusions')
    op.drop_index(op.f('ix_vendor_config_vendor_id'), table_name='vendor_config')
    op.drop_table('vendor_config')
    op.drop_table('system_config')
    op.drop_index(op.f('ix_lender_vendor_preferences_vendor_id'), table_name='lender_vendor_preferences')
    op.drop_index(op.f('ix_lender_vendor_preferences_lender_id'), table_name='lender_vendor_preferences')
    op.drop_table('lender_vendor_preferences')
    op.drop_index(op.f('ix_lender_config_lender_id'), table_name='lender_config')
    op.drop_table('lender_config')
    # ### end Alembic commands ###
