"""add listing coordinates

Revision ID: 3a447c6b0f50
Revises: 8df32c92c3dc
Create Date: 2026-04-11 10:43:02.849261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a447c6b0f50'
down_revision: Union[str, None] = '8df32c92c3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('listings', sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'longitude')
    op.drop_column('listings', 'latitude')
    # ### end Alembic commands ###
