"""add invoice_number line_items_count notes to invoices

Revision ID: 3a9487f0bd13
Revises: e976464c28ef
Create Date: 2026-04-12 11:17:29.032728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9487f0bd13'
down_revision: Union[str, None] = 'e976464c28ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_number', sa.String(length=30), nullable=True))
    op.add_column('invoices', sa.Column('line_items_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('invoices', sa.Column('notes', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_invoices_invoice_number', 'invoices', ['invoice_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invoices_invoice_number', 'invoices', type_='unique')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'line_items_count')
    op.drop_column('invoices', 'invoice_number')
    # ### end Alembic commands ###
