"""add bulk_upload_jobs table and extraction_failed status

Revision ID: 5d2ef40d3403
Revises: e93070d39d11
Create Date: 2026-04-10 02:49:49.065045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2ef40d3403'
down_revision: Union[str, None] = 'e93070d39d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_upload_jobs',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('total_reports', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'PARTIALLY_FAILED', name='bulkuploadstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reports', sa.Column('bulk_upload_job_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'reports', 'bulk_upload_jobs', ['bulk_upload_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'bulk_upload_job_id')
    op.drop_table('bulk_upload_jobs')
    # ### end Alembic commands ###
