"""add vendor profile and rating tables

Revision ID: 69118841ebe4
Revises: 038e25c5619a
Create Date: 2026-04-13 03:50:21.059247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69118841ebe4'
down_revision: Union[str, None] = '038e25c5619a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_profiles',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('display_photo', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('founding_year', sa.Integer(), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('specialization_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vendor_tier', sa.Enum('NEW', 'VERIFIED', 'TOP_VALUER', name='vendortier'), nullable=False),
    sa.Column('tier_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tier_warning_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_completeness', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id', name='uq_vendor_profile_vendor')
    )
    op.create_index(op.f('ix_vendor_profiles_vendor_id'), 'vendor_profiles', ['vendor_id'], unique=False)
    op.create_table('vendor_ratings',
    sa.Column('lender_user_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('report_request_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_request_id'], ['report_requests.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_request_id', name='uq_vendor_rating_request')
    )
    op.create_index(op.f('ix_vendor_ratings_lender_user_id'), 'vendor_ratings', ['lender_user_id'], unique=False)
    op.create_index(op.f('ix_vendor_ratings_report_request_id'), 'vendor_ratings', ['report_request_id'], unique=False)
    op.create_index(op.f('ix_vendor_ratings_vendor_id'), 'vendor_ratings', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_ratings_vendor_id'), table_name='vendor_ratings')
    op.drop_index(op.f('ix_vendor_ratings_report_request_id'), table_name='vendor_ratings')
    op.drop_index(op.f('ix_vendor_ratings_lender_user_id'), table_name='vendor_ratings')
    op.drop_table('vendor_ratings')
    op.drop_index(op.f('ix_vendor_profiles_vendor_id'), table_name='vendor_profiles')
    op.drop_table('vendor_profiles')
    # ### end Alembic commands ###
