"""add price band and vendor pricing tables

Revision ID: a08c82469283
Revises: 0630bde9396d
Create Date: 2026-04-13 04:05:08.758420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08c82469283'
down_revision: Union[str, None] = '0630bde9396d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use raw SQL to reference existing enum types
    op.execute("""
        CREATE TABLE price_bands (
            id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
            city VARCHAR(255) NOT NULL,
            property_type propertytype NOT NULL,
            report_category reportcategory NOT NULL,
            min_price NUMERIC(12,2) NOT NULL,
            max_price NUMERIC(12,2) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_price_band_city_type_category UNIQUE (city, property_type, report_category)
        )
    """)
    op.execute("""
        CREATE TABLE vendor_pricing (
            id UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
            vendor_id UUID NOT NULL REFERENCES vendors(id),
            city VARCHAR(255) NOT NULL,
            property_type propertytype NOT NULL,
            report_category reportcategory NOT NULL,
            price NUMERIC(12,2) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_vendor_pricing_vendor_city_type_category UNIQUE (vendor_id, city, property_type, report_category)
        )
    """)
    op.execute("CREATE INDEX ix_vendor_pricing_vendor_id ON vendor_pricing (vendor_id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_pricing_vendor_id'), table_name='vendor_pricing')
    op.drop_table('vendor_pricing')
    op.drop_table('price_bands')
    # ### end Alembic commands ###
