"""add phase 2 pricing report listing request billing models

Revision ID: e93070d39d11
Revises: da71d8a03b9c
Create Date: 2026-04-09 19:10:25.034301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e93070d39d11'
down_revision: Union[str, None] = 'da71d8a03b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('macro_location', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('property_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', 'AGRICULTURAL', name='propertytype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'AVAILABLE', 'ARCHIVED', name='listingstatus'), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('latest_report_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('invoice_type', sa.Enum('PAYABLE', 'RECEIVABLE', name='invoicetype'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BILLED', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_rules',
    sa.Column('lender_id', sa.Uuid(), nullable=False),
    sa.Column('report_category', sa.Enum('VALUATION', 'LEGAL', name='reportcategory'), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('property_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', 'AGRICULTURAL', name='propertytype'), nullable=False),
    sa.Column('new_request_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('listing_download_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('update_additional_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('nearby_additional_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lender_id', 'report_category', 'city', 'area', 'property_type', name='uq_pricing_rule_with_area')
    )
    op.create_index('uq_pricing_rule_without_area', 'pricing_rules', ['lender_id', 'report_category', 'city', 'property_type'], unique=True, postgresql_where='area IS NULL')
    op.create_table('reports',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('report_category', sa.Enum('VALUATION', 'LEGAL', name='reportcategory'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'READY_TO_PUBLISH', 'PUBLISHED', 'ARCHIVED', name='reportstatus'), nullable=False),
    sa.Column('property_address', sa.String(length=500), nullable=True),
    sa.Column('macro_location', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('property_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', 'AGRICULTURAL', name='propertytype'), nullable=True),
    sa.Column('plot_extent_sqft', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('built_up_sqft', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valuation_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('loan_applicant_name', sa.String(length=255), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_file_path', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('listing_approved', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing_reports',
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', name='uq_listing_report_report_id')
    )
    op.create_table('report_requests',
    sa.Column('lender_id', sa.Uuid(), nullable=False),
    sa.Column('lender_user_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('request_type', sa.Enum('NEW', 'UPDATE', 'NEARBY', name='requesttype'), nullable=False),
    sa.Column('report_category', sa.Enum('VALUATION', 'LEGAL', name='reportcategory'), nullable=False),
    sa.Column('num_reports_needed', sa.Integer(), nullable=False),
    sa.Column('property_address', sa.String(length=500), nullable=True),
    sa.Column('property_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', 'AGRICULTURAL', name='propertytype'), nullable=False),
    sa.Column('plot_extent_sqft', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('loan_applicant_name', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('eta_days', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vendor_specified_id', sa.Uuid(), nullable=True),
    sa.Column('allow_broadcast_on_reject', sa.Boolean(), nullable=False),
    sa.Column('parent_report_id', sa.Uuid(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('lender_status', sa.Enum('DRAFT', 'SENT', 'AWAITED', 'RECEIVED', 'ACCEPTED', 'SENT_FOR_REVIEW', 'REJECTED', name='lenderrequeststatus'), nullable=False),
    sa.Column('vendor_status', sa.Enum('INCOMING', 'DENIED', 'PENDING', 'SENT', 'ACCEPTED', 'REVISION', name='vendorrequeststatus'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['lender_branches.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['lender_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['vendor_specified_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_revisions',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('changes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lender_payables',
    sa.Column('lender_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payable_type', sa.Enum('NEW_REQUEST', 'LISTING_DOWNLOAD', 'UPDATE', 'NEARBY', name='payabletype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'BILLED', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['report_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_acceptances',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['report_requests.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request_broadcasts',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('broadcast_round', sa.Integer(), nullable=False),
    sa.Column('accept_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'ACCEPTED', name='broadcaststatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['report_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_earnings',
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('lender_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('earning_type', sa.Enum('REQUEST', 'LISTING_DOWNLOAD', name='earningtype'), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['report_requests.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_earnings')
    op.drop_table('request_broadcasts')
    op.drop_table('request_acceptances')
    op.drop_table('lender_payables')
    op.drop_table('report_revisions')
    op.drop_table('report_requests')
    op.drop_table('listing_reports')
    op.drop_table('reports')
    op.drop_index('uq_pricing_rule_without_area', table_name='pricing_rules', postgresql_where='area IS NULL')
    op.drop_table('pricing_rules')
    op.drop_table('invoices')
    op.drop_table('listings')
    # ### end Alembic commands ###
